name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - prod
  pull_request:
    branches:
      - dev
      - prod
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy to production'
        required: true
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Run tests
      env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      run: |
        poetry run pytest app/tests

  deploy-staging:
    needs: test
    if: github.ref == 'refs/heads/dev' || (github.event_name == 'pull_request' && github.base_ref == 'dev')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku Staging
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ secrets.HEROKU_STAGING_APP }}.git HEAD:main

  test-staging:
    needs: deploy-staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Run staging tests
      env:
        ENV: staging
        SUPABASE_URL: ${{ secrets.SUPABASE_STAGING_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_STAGING_KEY }}
        BASE_URL: ${{ secrets.STAGING_URL }}
      run: |
        poetry run pytest app/tests

  deploy-production:
    needs: [test, test-staging]
    if: github.ref == 'refs/heads/prod' || (github.event.inputs.environment == 'production' && github.ref == 'refs/heads/dev')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Heroku Production
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git push https://heroku:$HEROKU_API_KEY@git.heroku.com/${{ secrets.HEROKU_PRODUCTION_APP }}.git HEAD:main

  test-production:
    needs: deploy-production
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Run production tests
      env:
        ENV: production
        SUPABASE_URL: ${{ secrets.SUPABASE_PROD_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_PROD_KEY }}
        BASE_URL: ${{ secrets.PRODUCTION_URL }}
      run: |
        poetry run pytest app/tests